[package]
name = "dvc-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflink = "0.1.3"
hex = "0.4.3"
sqlite = "0.26.0"
console = "0.15.0"
num_cpus = "1.13.1"
md-5 = "0.10.1"
json = "0.12.4"
rayon = "1.5.3"
jwalk = "0.6.0"
base16ct = { version = "0.1.1", features = ["alloc"] }
clap = { version = "3.2.8", features = ["derive"] }
indicatif = { version = "0.16.2", features = ["rayon"] }

[profile.release]
lto = "fat"
panic = "abort"
debug = true
codegen-units = 1
