[package]
name = "dvc-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflink = "0.1.3"
hex = "0.4.3"
console = "0.15.7"
num_cpus = "1.16.0"
md-5 = "0.10.6"
rayon = "1.8.0"
jwalk = "0.8.1"
base16ct = { version = "0.2.0", features = ["alloc"] }
clap = { version = "4.4.8", features = ["derive"] }
indicatif = { version = "0.17.7", features = ["rayon"] }
rusqlite = { version = "0.30.0", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
serde_yaml = "0.9"
ignore = "0.4.20"
itertools = "0.12.0"
env_logger = "0.10.1"
log = "0.4.20"
uzers = "0.11.3"
config = "0.13.3"
serde_derive = "1.0.192"
directories = "5.0.1"
git2 = "0.18.1"

[dev-dependencies]
tempfile = "3.8.1"

[profile.release]
debug = true
lto = "fat"
panic = "abort"
codegen-units = 1

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
perf = "warn"
pedantic = "warn"
case_sensitive_file_extension_comparisons = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
return_self_not_must_use = "allow"
