name: CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --all --check
      - run: cargo clippy --all-targets --all-features
      - run: cargo test
      - run: cargo build --verbose
      - run: cargo build --release --verbose
      - run: cargo build --profile dist --verbose
